services:
  plan-fact:
    container_name: plan-fact
    image: plan-fact
    build:
      context: ./backend
      dockerfile: Dockerfile
    labels:
      - "nginx.auth=true"
      - "nginx.client_max_body_size=100m"  # Increase max upload size to 100MB
    volumes:
      - ./excel_data:/app/excel_data
      - ./instance:/app/instance
      - ./backend/static:/app/static
      - ./backend/templates:/app/templates
    environment:
      - BEHIND_PROXY=true
    env_file:
      - ./backend/.env  
    networks:
      - service_network
      - public_network

networks:
  service_network:
    external: true
    name: service_network
  public_network:
    external: true
    name: public_network

